[package]
name = "spike-hid"
version = "0.1.0"
edition = "2024"

[dependencies]
hidapi = "2"
rusb = { version = "0.9.4", features = ["vendored"] }
windows-sys = { version = "0.61.2", features = ["Win32_Foundation", "Win32_Storage_FileSystem", "Win32_System_IO", "Win32_Devices_HumanInterfaceDevice", "Win32_Security"] }
