[package]
name = "motor"
version = "1.0.0"
edition = "2024"
license = "GPL-3.0-only"
authors = ["Thryki <davireis@proton.me>"]
repository = "https://github.com/Thryki/mikrodeck"

[lib]
name = "motor"
path = "src/lib.rs"

[[bin]]
name = "motor"
path = "src/main.rs"

[dependencies]
cpal = "0.16"
dirs = "6.0.0"
hidapi = "2.6.7"
hound = "3.5"
rodio = { version = "0.21", default-features = false, features = ["playback", "symphonia-all", "wav", "flac"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
ureq = { version = "3.4.0", default-features = false, features = ["json", "rustls"] }
windows = { version = "0.62.2", features = ["Win32_Media_Audio", "Win32_System_Com", "Win32_Foundation", "Win32_Media_Audio_Endpoints", "Win32_System_Com_StructuredStorage", "Win32_System_Variant"] }
windows-sys = { version = "0.61.2", features = [
  "Win32_UI_Input_KeyboardAndMouse",
  "Win32_Foundation",
  "Win32_Media_Audio",
  "Win32_System_Com",
  "Win32_System_Com_StructuredStorage",
  "Win32_System_ProcessStatus",
  "Win32_System_Variant",
  "Win32_UI_WindowsAndMessaging",
  "Win32_System_Threading",
  "Win32_System_Diagnostics_ToolHelp",
] }
