[package]
name = "motor"
version = "0.1.0"
edition = "2024"

[lib]
name = "motor"
path = "src/lib.rs"

[[bin]]
name = "motor"
path = "src/main.rs"

[dependencies]
dirs = "6.0.0"
hidapi = "2.6.7"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
ureq = { version = "3.4.0", default-features = false, features = ["json", "rustls"] }
windows = { version = "0.62.2", features = ["Win32_Media_Audio", "Win32_System_Com", "Win32_Foundation", "Win32_Media_Audio_Endpoints", "Win32_System_Com_StructuredStorage", "Win32_System_Variant"] }
windows-sys = { version = "0.61.2", features = [
  "Win32_UI_Input_KeyboardAndMouse",
  "Win32_Foundation",
  "Win32_Media_Audio",
  "Win32_System_Com",
  "Win32_System_Com_StructuredStorage",
  "Win32_System_ProcessStatus",
  "Win32_System_Variant",
  "Win32_UI_WindowsAndMessaging",
  "Win32_System_Threading",
  "Win32_System_Diagnostics_ToolHelp",
] }
