[package]
name = "mikrodeck"
version = "1.0.0"
description = "MikroDeck — o Maschine Mikro MK3 como Stream Deck"
authors = ["Thryki"]
edition = "2021"
license = "GPL-3.0-only"
authors = ["Thryki <davireis@proton.me>"]
repository = "https://github.com/Thryki/mikrodeck"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "mikrodeck_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon", "image-png"] }
tauri-plugin-opener = "2"
motor = { path = "../../motor" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-dialog = "2.7.3"
tauri-plugin-autostart = "2.5.1"

